### ISSUE TITLE
how to create  in  grid value in unity with 1.3.6

### ISSUE THREAD

**Issue by bigtrizero** [Cammin/LDtkUnity#12]
how to create  in  grid value in unity with 1.3.6?

![未标题-1](https://user-images.githubusercontent.com/1180770/114017966-492f7100-989f-11eb-8651-697301c81789.jpg)

and  need a feature  ,  need  convert  in grid value  to  unity tilemap layer

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address issue](https://trello.com/c/moQKXHwA/232-address-issue)

**Comment by Cammin** [comment]
Int grid values in LDtk are displayed inside of the LDtk Project asset inspector as their own section for Int Grid Values. 

For each int grid value, there is a sprite field, which allows you to define collisions.
In the scene, displaying tiles visually is entirely handled by the Tile layers. if that is what you were wondering about.
Alternatively, you can set the option to make the int grid values visible, and their corresponding colours will be displayed on the generated tilemaps in the scene.

Let me know if this helped out, or if you were wondering about something else. I'll try and provide some images some time later

**Comment by supertrizero** [comment]
yes It's help! thank you.  

now  I have a problem

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/5143332/114207922-7b200080-998f-11eb-85bb-4723049d89f5.png">

in ldtk ,  I create  en  entitie  ladder  16x128 , and in unity  it  set  scale  to 8 ，It causes the deformation of the child game object and changes the position of the child game object.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/5143332/114208515-229d3300-9990-11eb-9f53-49814dde78fe.png">

<img width="290" alt="image" src="https://user-images.githubusercontent.com/5143332/114208971-aeaf5a80-9990-11eb-95d1-95af5a7412e4.png">

<img width="67" alt="image" src="https://user-images.githubusercontent.com/5143332/114209031-c25ac100-9990-11eb-86bc-c991996dbf86.png">

**Comment by Cammin** [comment]
Ah, I can give you some more insight on this. 

Here's what is happening here:
- The object's scale gets set to 8 because it's based on how much the entity was resized in LDtk. (see below)
- The deformation of the child happens because the parent's scale was set to 8. (Maybe I should allow customization of how the scale should be applied perhaps 😄 )
- I'm unsure how the child's local position may have been changed, so I'd be interested in figuring out how that could be happening. Maybe it's because of the object's pivot point relative to the center of the box collider?

I actually have to document that resizing entities affect the unity object's scale. 
Here's the subject:

# Entity Scale Determination
When an entity's prefab is instantiated, that object's scale adjusts accordingly if the entity instance was resized in LDtk. 
 
The scale value is determined by the difference between the original entity size and the resized entity in LDtk.
So when making the prefab for an entity instance, make the prefab match the exact same scale size as the entity's definition in LDtk, and not the resized entity instance.

Example: In LDtk, an entity's definition size is 16x16 pixels. If an entity instance resized to 32x48 pixels in size in the level, then the scale value in unity would be: (2, 3, 1)

**Comment by Cammin** [comment]
I pushed a new major update that may fix this issue. Let me know if the new process works for you, or if you still have any problems with this issue 🙂

**Comment by Cammin** [comment]
I'm leaving this issue as resolved, but feel free to reopen (or post new different issue) if necessary 🙂
