### ISSUE TITLE
Unity GUID error

### ISSUE THREAD

**Issue by stickynoteme** [Cammin/LDtkUnity#23]
updated LDtkUnity today and now I'm getting this error:

```
GUID [8c4bfcb5b17948478ccb955bccff9652] for asset 'Packages/com.unity.nuget.newtonsoft-json/Runtime/Newtonsoft.Json.dll' conflicts with:
  'Packages/jillejr.newtonsoft.json-for-unity/Plugins/Newtonsoft.Json Editor/Newtonsoft.Json.dll' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
```

Looks like LDtkUnity installed jillejr.newtonsoft.json-for-unity and it's conflicted with the built in com.unity.nuget.newtonsoft-json.

Not sure what to do about this.

**Comment by Cammin** [comment]
Hmm, some sort of package conflict issue. I'll investigate and try to figure this out. Thank you for the report. 🙂

**Comment by Cammin** [comment]
I believe I've found a solution from these threads.  
https://forum.unity.com/threads/newtonsoft-json-error-after-upgrading-to-0-8-1-from-0-6.961198/  
https://forum.unity.com/threads/newtonsoft-json-package.843220/  

Basically, I was using the standard [Json.Net](https://github.com/jilleJr/Newtonsoft.Json-for-Unity) package from their GitHub, but Unity made [their own version](https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@1.1/manual/index.html) of Json.Net, so I'll try using that instead which may solve the problem. 

Maybe you got this problem because you have another package that uses Unity's version of Json.Net?

**Comment by Cammin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix GUID bug related to json.net package conflicts](https://trello.com/c/6vplugNp/367-fix-guid-bug-related-to-jsonnet-package-conflicts)

**Comment by Cammin** [comment]
I've tried fixing this. I pushed a new update that changes the dependent Package from [Newtonsoft Json for Unity](https://github.com/jilleJr/Newtonsoft.Json-for-Unity) to [Newtonsoft Json Unity Package](https://docs.unity3d.com/Packages/com.unity.nuget.newtonsoft-json@2.0/manual/index.html).

[Changelog](https://github.com/Cammin/LDtkToUnity/blob/master/Assets/LDtkUnity/CHANGELOG.md)

Overall, it should help prevent some clashing. The error might appear one more time, but won't appear any further after that, I think. 🙂 

Feel free to reopen this issue if something unexpected still happens.
