### ISSUE TITLE
Weird Coloring issue.

### ISSUE THREAD

**Issue by CJFEdu** [Cammin/LDtkUnity#40]
I'm just testing things out using the Cavernous tile set that comes with LDtk and I'm getting this weird coloring issue.  In LDtk the lava looks like this.

![image](https://user-images.githubusercontent.com/87827435/202647391-c1195c62-88de-48e0-85a9-5b784944a2e8.png)

But in Unity it looks like this.
![image](https://user-images.githubusercontent.com/87827435/202647512-c69c9f9b-5314-4564-af1b-0b5ac1a8c649.png)

You can see the line in the lava in the Unity version where the colors are supposed to be the same.  Also it's a lot blurrier.  I'm assuming there's a conversion problem somewhere.  I'm using a sprite atlas, so maybe in the creation of the sprites it's causing it.  Not sure.

**Comment by Cammin** [comment]
The blurry issues lies within with the import settings of the sprite atlas and the source texture. 
Check with both that their filter mode is set to "Point", this causes the blur.

For the color issue, it's possibly due to the compression settings. Try changing the format to "RGBA 32 bit" and that should fix the discoloured image.

If the issue is still there, double check with both the sprite atlas and the source texture that those import settings are set.

Let me know if that fixes your issue 🙂

**Comment by CJFEdu** [comment]
Thanks for the quick response.  Solved both problems.  The package is fantastic by the way.  Absolutely loving it so far.

**Comment by Cammin** [comment]
Awesome, glad it's working for you. Let me know if you have any other issues in the discord 🙂
