### ISSUE TITLE
I need a feature（can set layer name in ldtk or in unity)

### ISSUE THREAD

**Issue by bigtrizero** [Cammin/LDtkUnity#8]
I need a feature（can set layer name in ldtk and Convert to Unity   or   set layer name directly  in unity)

The Layer will now be reset when rebuilding the project.

Please forgive me for my poor English。

**Comment by Cammin** [comment]
This sounds like a neat idea, to be able to transfer tags data from LDtk over to layers/entities.

I will explore some options when I get around to it and evaluate the best solution and explain it here.

In LDtk, there are tag options for entities, but not layers (I think), but I'll see what would be a good solution for entities, intgrid layers, and tile layers. 🙂

For layers, I may try adding layer mask options in the LDtk Project asset.

**Comment by Cammin** [comment]
To answer your question in the short term, there is an option to change what the default generated tilemap object is.
![image](https://user-images.githubusercontent.com/55564581/111836349-5914f000-88b3-11eb-96cd-ce1b47aeed16.png)

Steps to make a custom prefab are here: https://github.com/Cammin/LDtkUnity/wiki/Tilemap-Grid-Prefab
Your custom prefab would have the Tag/LayerMask changes :)

However this would affect all layers, so it may not be the exact solution you are looking for, but I'm planning to implement a feature where a Grid prefab can be set for every layer instead of all of them.

**Comment by Cammin** [comment]
Here's how it looks so far, sitting next to the layers in LDtk.
![image](https://user-images.githubusercontent.com/55564581/112045414-10a24000-8b08-11eb-9064-0498282a866d.png)
This should help out with many customizable options related to the prefab itself, like specifying different tags, layerMask, material/shader, physics material, or anything else. 👍

**Comment by supertrizero** [comment]
It works great! Thank you so much!

**Comment by Cammin** [comment]
I pushed the update with this feature. Hopefully, there are no bugs :)
https://github.com/Cammin/LDtkUnity/blob/master/CHANGELOG.md
